# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.timesheet_period_api import TimesheetPeriodApi


class TestTimesheetPeriodApi(unittest.TestCase):
    """TimesheetPeriodApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TimesheetPeriodApi()

    def tearDown(self) -> None:
        pass

    def test_create_timesheet_period(self) -> None:
        """Test case for create_timesheet_period

        Create TimesheetPeriods
        """
        pass

    def test_delete_timesheet_period(self) -> None:
        """Test case for delete_timesheet_period

        Delete TimesheetPeriods
        """
        pass

    def test_get_timesheet_period(self) -> None:
        """Test case for get_timesheet_period

        Read TimesheetPeriods
        """
        pass

    def test_get_timesheet_period_field_length(self) -> None:
        """Test case for get_timesheet_period_field_length

        View TimesheetPeriod Field Length
        """
        pass

    def test_get_timesheet_period_fields(self) -> None:
        """Test case for get_timesheet_period_fields

        View TimesheetPeriod fields
        """
        pass

    def test_update_timesheet_period(self) -> None:
        """Test case for update_timesheet_period

        Update TimesheetPeriods
        """
        pass


if __name__ == '__main__':
    unittest.main()
