# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.resource_team_api import ResourceTeamApi


class TestResourceTeamApi(unittest.TestCase):
    """ResourceTeamApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResourceTeamApi()

    def tearDown(self) -> None:
        pass

    def test_create_resource_team(self) -> None:
        """Test case for create_resource_team

        Create ResourceTeam
        """
        pass

    def test_delete_resource_team(self) -> None:
        """Test case for delete_resource_team

        Delete ResourceTeam
        """
        pass

    def test_get_resource_team(self) -> None:
        """Test case for get_resource_team

        Read ResourceTeam
        """
        pass

    def test_get_resource_team_field_length(self) -> None:
        """Test case for get_resource_team_field_length

        View ResourceTeam Field Length
        """
        pass

    def test_get_resource_team_fields(self) -> None:
        """Test case for get_resource_team_fields

        View ResourceTeam fields
        """
        pass

    def test_update_resource_team(self) -> None:
        """Test case for update_resource_team

        Update ResourceTeam
        """
        pass


if __name__ == '__main__':
    unittest.main()
