# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.project_deployment_api import ProjectDeploymentApi


class TestProjectDeploymentApi(unittest.TestCase):
    """ProjectDeploymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectDeploymentApi()

    def tearDown(self) -> None:
        pass

    def test_create_project_deployment(self) -> None:
        """Test case for create_project_deployment

        Create ProjectDeployment
        """
        pass

    def test_delete_project_deployment(self) -> None:
        """Test case for delete_project_deployment

        Delete ProjectDeployment
        """
        pass

    def test_get_project_deployment(self) -> None:
        """Test case for get_project_deployment

        Read ProjectDeployment
        """
        pass

    def test_get_project_deployment_field_length(self) -> None:
        """Test case for get_project_deployment_field_length

        View ProjectDeployment Field Length
        """
        pass

    def test_get_project_deployment_fields(self) -> None:
        """Test case for get_project_deployment_fields

        View ProjectResourceQuantity fields
        """
        pass

    def test_update_project_deployment(self) -> None:
        """Test case for update_project_deployment

        Update ProjectDeployment
        """
        pass


if __name__ == '__main__':
    unittest.main()
