# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.resource_assignment_create_api import ResourceAssignmentCreateApi


class TestResourceAssignmentCreateApi(unittest.TestCase):
    """ResourceAssignmentCreateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResourceAssignmentCreateApi()

    def tearDown(self) -> None:
        pass

    def test_create_resource_assignment_create(self) -> None:
        """Test case for create_resource_assignment_create

        Create ResourceAssignmentCreate
        """
        pass

    def test_delete_resource_assignment_create(self) -> None:
        """Test case for delete_resource_assignment_create

        Delete ResourceAssignmentCreate
        """
        pass

    def test_get_resource_assignment_create(self) -> None:
        """Test case for get_resource_assignment_create

        Read ResourceAssignmentCreate
        """
        pass

    def test_get_resource_assignment_create_field_length(self) -> None:
        """Test case for get_resource_assignment_create_field_length

        View ResourceAssignmentCreate Field Length
        """
        pass

    def test_get_resource_assignment_create_fields(self) -> None:
        """Test case for get_resource_assignment_create_fields

        View ResourceAssignmentCreate fields
        """
        pass

    def test_update_resource_assignment_create(self) -> None:
        """Test case for update_resource_assignment_create

        Update ResourceAssignmentCreate
        """
        pass


if __name__ == '__main__':
    unittest.main()
