# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.activity_note_api import ActivityNoteApi


class TestActivityNoteApi(unittest.TestCase):
    """ActivityNoteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivityNoteApi()

    def tearDown(self) -> None:
        pass

    def test_create_activity_notes(self) -> None:
        """Test case for create_activity_notes

        Create ActivityNotes
        """
        pass

    def test_delete_activity_notes(self) -> None:
        """Test case for delete_activity_notes

        Delete ActivityNotes
        """
        pass

    def test_get_activity_notes(self) -> None:
        """Test case for get_activity_notes

        Read ActivityNotes
        """
        pass

    def test_get_activity_notes_field_length(self) -> None:
        """Test case for get_activity_notes_field_length

        View ActivityNote Field Length
        """
        pass

    def test_get_activity_notes_fields(self) -> None:
        """Test case for get_activity_notes_fields

        View ActivityNote fields
        """
        pass

    def test_put_activity_notes(self) -> None:
        """Test case for put_activity_notes

        Update ActivityNotes
        """
        pass


if __name__ == '__main__':
    unittest.main()
