# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ResourceRoleExport(BaseModel):
    """
    ResourceRole Entity
    """ # noqa: E501
    include: Optional[StrictBool] = Field(default=None, description="Boolean flag that indicates whether the associated object is to be exported. The default value of the Include element is true. To exclude a business object from the XML export file, specify false in the Include element for that business object.", alias="Include")
    var_field: Optional[List[StrictStr]] = Field(default=None, description="List of Fields for ResourceRole Business Object", alias="Field")
    __properties: ClassVar[List[str]] = ["Include", "Field"]

    @field_validator('var_field')
    def var_field_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['CREATE_DATE', 'CREATE_USER', 'LAST_UPDATE_DATE', 'LAST_UPDATE_USER', 'PROFICIENCY', 'RESOURCE_ID', 'RESOURCE_NAME', 'RESOURCE_OBJECT_ID', 'ROLE_ID', 'ROLE_NAME', 'ROLE_OBJECT_ID']):
                raise ValueError("each list item must be one of ('CREATE_DATE', 'CREATE_USER', 'LAST_UPDATE_DATE', 'LAST_UPDATE_USER', 'PROFICIENCY', 'RESOURCE_ID', 'RESOURCE_NAME', 'RESOURCE_OBJECT_ID', 'ROLE_ID', 'ROLE_NAME', 'ROLE_OBJECT_ID')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceRoleExport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceRoleExport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Include": obj.get("Include"),
            "Field": obj.get("Field")
        })
        return _obj


