# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RiskMatrix(BaseModel):
    """
    RiskMatrix Entity
    """ # noqa: E501
    create_date: Optional[datetime] = Field(default=None, description="The date this risk matrix was created.", alias="CreateDate")
    create_user: Optional[StrictStr] = Field(default=None, description="The name of the user that created the risk matrix.", alias="CreateUser")
    description: Optional[StrictStr] = Field(default=None, description="The description of the risk matrix.", alias="Description")
    impact_threshold_level: Optional[StrictInt] = Field(default=None, description="The number of levels for the impact thresholds assigned to the risk scoring matrix. This impact level with the probability level determines the size of the matrix.", alias="ImpactThresholdLevel")
    last_update_date: Optional[datetime] = Field(default=None, description="The date this risk matrix was last updated.", alias="LastUpdateDate")
    last_update_user: Optional[StrictStr] = Field(default=None, description="The name of the user that last updated the risk matrix.", alias="LastUpdateUser")
    name: StrictStr = Field(description="The name of the risk matrix.", alias="Name")
    object_id: Optional[StrictInt] = Field(default=None, description="The unique ID generated by the system.", alias="ObjectId")
    probability_threshold_level: Optional[StrictInt] = Field(default=None, description="The number of levels for the probability threshold assigned to the risk matrix. This probability level with the impact level determines the size of the matrix.", alias="ProbabilityThresholdLevel")
    risk_scoring_method: Optional[StrictStr] = Field(default=None, description="The calculation method used to determine the risk score. Valid values are 'Highest', 'Average of Impacts', 'Average of Individual Scores'.", alias="RiskScoringMethod")
    __properties: ClassVar[List[str]] = ["CreateDate", "CreateUser", "Description", "ImpactThresholdLevel", "LastUpdateDate", "LastUpdateUser", "Name", "ObjectId", "ProbabilityThresholdLevel", "RiskScoringMethod"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskMatrix from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskMatrix from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CreateDate": obj.get("CreateDate"),
            "CreateUser": obj.get("CreateUser"),
            "Description": obj.get("Description"),
            "ImpactThresholdLevel": obj.get("ImpactThresholdLevel"),
            "LastUpdateDate": obj.get("LastUpdateDate"),
            "LastUpdateUser": obj.get("LastUpdateUser"),
            "Name": obj.get("Name"),
            "ObjectId": obj.get("ObjectId"),
            "ProbabilityThresholdLevel": obj.get("ProbabilityThresholdLevel"),
            "RiskScoringMethod": obj.get("RiskScoringMethod")
        })
        return _obj


