# coding: utf-8

"""
    P6 EPPM Rest API

    The Primavera P6 Enterprise Project Portfolio Management (P6 EPPM) API is a flexible interface to P6 EPPM functionality based on the Representational State Transfer (REST) architectural style. Clients can use HTTP enabled technologies to interact with the API and access application features. For example, you can write programs in Javascript, Java, and other languages to create users, view a list of users, update a user's status, or update user details.

    The version of the OpenAPI document: 2022.12.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.resource_requests import ResourceRequests
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User Entity
    """ # noqa: E501
    all_resource_access_flag: Optional[StrictBool] = Field(default=None, description="The flag that determines whether the user has all resource access (TRUE) or restricted resource access (FALSE). Admin Superusers always have all resource access.", alias="AllResourceAccessFlag")
    assignment_staffing_preference: Optional[StrictStr] = Field(default=None, description="The value that determines whether the current or the new resource's Units per Time and Overtime factor is used to calculate costs when assigning the resource to an existing activity assignment. If the AssignmentStaffingPreference is set to 'Ask Me', the default value is then current resource.", alias="AssignmentStaffingPreference")
    create_date: Optional[datetime] = Field(default=None, description="The date this user was created.", alias="CreateDate")
    create_user: Optional[StrictStr] = Field(default=None, description="The name of the user that created this user.", alias="CreateUser")
    currency_id: Optional[StrictStr] = Field(default=None, description="The unique currency abbreviation for the currency associated with this user.", alias="CurrencyId")
    currency_name: Optional[StrictStr] = Field(default=None, description="The name of the currency associated with this user.", alias="CurrencyName")
    currency_object_id: Optional[StrictInt] = Field(default=None, description="The unique ID of the associated currency.", alias="CurrencyObjectId")
    currency_show_decimals: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show decimal places for the currency, and when set to false will not Display decimal places. Possible values : 'True' or 'False'", alias="CurrencyShowDecimals")
    currency_show_symbol: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show Currency Symbol for the currency, and when set to false will not Display Currency Symbol. Possible values : 'True' or 'False'", alias="CurrencyShowSymbol")
    date_format_type: Optional[StrictStr] = Field(default=None, description="The date format type for the user: 'Month, Day, Year' , 'Day, Month, Year' or 'Year, Month, Day'.", alias="DateFormatType")
    date_separator: Optional[StrictStr] = Field(default=None, description="The date Separator for the user: '/' , '-' or '.'", alias="DateSeparator")
    date_show_four_digit_year: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show four digit year for the Date format specified, and when set to false will not show four digit year. Possible values : 'True' or 'False'", alias="DateShowFourDigitYear")
    date_show_minutes: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show minutes value for the Time format specified, and when set to false will not show minutes value. Possible values : 'True' or 'False'", alias="DateShowMinutes")
    date_time_format_type: Optional[StrictStr] = Field(default=None, description="The date format type for the user: '12 hour (1:30 PM)' , '24 hour (13:30)' or 'Do not show time'.", alias="DateTimeFormatType")
    date_use_leading_zero: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show leading zero for the Date format specified, and when set to false will not show leading zero. Possible values : 'True' or 'False'", alias="DateUseLeadingZero")
    date_use_month_name: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show month value for the Date format specified, and when set to false will not show month value. Possible values : 'True' or 'False'", alias="DateUseMonthName")
    duration_decimal_count: Optional[StrictStr] = Field(default=None, description="The Duration Decimal count for the user is the number of decimal places to be displayed for the Duration. : '0','1' or '2'.", alias="DurationDecimalCount")
    duration_unit_type: Optional[StrictStr] = Field(default=None, description="The Duration Unit Type for the user is the Display Time units In: 'Hour','Day','Week','Month' or 'Year'.", alias="DurationUnitType")
    duration_use_fraction: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show units for the Duration, and when set to false will not show units. Possible values : 'True' or 'False'", alias="DurationUseFraction")
    email_address: Optional[StrictStr] = Field(default=None, description="The current user's return email address. This will be used in the \"FROM\" line for any email sent by this user. Example: \"yourname@yourdomain.com\". For MAPI users, this may just be the MAPI profile name or mailbox name.", alias="EmailAddress")
    email_protocol: Optional[StrictStr] = Field(default=None, description="The email type for the user: 'Internet Mail' or 'MAPI Mail'.", alias="EmailProtocol")
    enable_user_to_modify_view_settings_flag: Optional[StrictBool] = Field(default=None, description="The flag that when set to true allows the user to change his or her personal view settings in P6. When a user changes the user interface view settings, the changes do not affect the settings of other users assigned to the same view.", alias="EnableUserToModifyViewSettingsFlag")
    financial_period_end_object_id: Optional[StrictInt] = Field(default=None, description="The unique ID generated by the system of the last financial period viewable in columns in Project Management.", alias="FinancialPeriodEndObjectId")
    financial_period_start_object_id: Optional[StrictInt] = Field(default=None, description="The unique ID generated by the system of the first financial period viewable in columns in Project Management.", alias="FinancialPeriodStartObjectId")
    guid: Optional[StrictStr] = Field(default=None, description="The globally unique ID generated by the system.", alias="GUID")
    global_profile_object_id: Optional[StrictInt] = Field(default=None, description="The unique ID of the global security profile assigned to the user. See the GlobalProfile class for constants defining the fixed profiles of Admin Superuser and No Global Privileges.", alias="GlobalProfileObjectId")
    last_update_date: Optional[datetime] = Field(default=None, description="The date this user was last updated.", alias="LastUpdateDate")
    last_update_user: Optional[StrictStr] = Field(default=None, description="The name of the user that last updated this user.", alias="LastUpdateUser")
    mail_server_login_name: Optional[StrictStr] = Field(default=None, description="The mail login name (profile name) for the current user to send outgoing email. If the email protocol is MAPI, this field should contain the MAPI profile name", alias="MailServerLoginName")
    name: Optional[StrictStr] = Field(default=None, description="The user's login name.", alias="Name")
    new_project_duration_type: Optional[StrictStr] = Field(default=None, description="the default duration type assigned to new activities. Valid values are 'Fixed Units/Time', 'Fixed Duration and Units/Time', 'Fixed Units', or 'Fixed Duration and Units'.", alias="NewProjectDurationType")
    object_id: Optional[StrictInt] = Field(default=None, description="The unique ID generated by the system.", alias="ObjectId")
    office_phone: Optional[StrictStr] = Field(default=None, description="The work phone number of the user.", alias="OfficePhone")
    outgoing_mail_server: Optional[StrictStr] = Field(default=None, description="The outgoing mail server (SMTP) address used to send outgoing email for this user. The address may be a host name or an IP address. This field is used only with the Internet email protocol, and is not required for MAPI.", alias="OutgoingMailServer")
    personal_name: Optional[StrictStr] = Field(default=None, description="The user's personal or actual name.", alias="PersonalName")
    rate_source_preference: Optional[StrictStr] = Field(default=None, description="The value that determines which price/unit will be used by default to calculate costs for the assignment when both a resource and role are assigned.", alias="RateSourcePreference")
    reporting_flag: Optional[StrictBool] = Field(default=None, description="The flag that determines whether the user can access ODS database as a database user.", alias="ReportingFlag")
    resource_requests: Optional[ResourceRequests] = Field(default=None, alias="ResourceRequests")
    respect_activity_duration_type: Optional[StrictBool] = Field(default=None, description="the setting that indicates whether to recalculate the Duration, Units, or Units/Time for existing assignments based on the activity Duration Type (true) or to preserve the Duration, Units, or Units/Time for existing assignments (false) when adding or removing assignments on activities.", alias="RespectActivityDurationType")
    role_limit_display_option: Optional[StrictStr] = Field(default=None, description="The option for how RoleLimit is displayed. Valid values are 'Custom', and 'PrimaryRole'.", alias="RoleLimitDisplayOption")
    show_duration_time_unit: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show units for the Duration, and when set to false will not show units. Possible values : 'True' or 'False'", alias="ShowDurationTimeUnit")
    show_time_unit: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show units for the Time, and when set to false will not show units. Possible values : 'True' or 'False'", alias="ShowTimeUnit")
    small_scale_decimal_count: Optional[StrictStr] = Field(default=None, description="The Small Scale Decimal count for the user is the number of decimal places to be displayed for the Time. : '0','1' or '2'.", alias="SmallScaleDecimalCount")
    small_scale_unit_type: Optional[StrictStr] = Field(default=None, description="The Small Scale Unit Type for the user is the Display Time units In: 'Hour','Day','Week','Month' or 'Year'.", alias="SmallScaleUnitType")
    small_scale_use_fraction: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show sub units for the Time units format specified, and when set to false will not show sub units. Possible values : 'True' or 'False'", alias="SmallScaleUseFraction")
    team_member_activity_filters: Optional[StrictStr] = Field(default=None, description="The Statuser activity filters for the Team Member application.", alias="TeamMemberActivityFilters")
    team_member_activity_sort_field: Optional[StrictStr] = Field(default=None, description="Select whether column name entries are sorted in ascending or descending order.", alias="TeamMemberActivitySortField")
    team_member_activity_sort_order: Optional[StrictStr] = Field(default=None, description="From the Sort Order list, you can select to list projects in the scorecard in either ascending", alias="TeamMemberActivitySortOrder")
    team_member_application_theme: Optional[StrictStr] = Field(default=None, description="The user interface theme setting for P6 Team Member Web.", alias="TeamMemberApplicationTheme")
    team_member_date_format: Optional[StrictStr] = Field(default=None, description="The date format setting for the P6 Team Member Web.", alias="TeamMemberDateFormat")
    team_member_display_time_flag: Optional[StrictBool] = Field(default=None, description="The display hours setting for P6 Team Member Web.", alias="TeamMemberDisplayTimeFlag")
    team_member_display_time_format: Optional[StrictStr] = Field(default=None, description="The display hours format setting for P6 Team Member Web.", alias="TeamMemberDisplayTimeFormat")
    team_member_locale: Optional[StrictStr] = Field(default=None, description="The user-specific locale set for P6 Team Member Web.", alias="TeamMemberLocale")
    team_member_project_filter: Optional[StrictStr] = Field(default=None, description="The project filter for P6 Team Member Web.", alias="TeamMemberProjectFilter")
    team_member_resource_filter: Optional[StrictStr] = Field(default=None, description="The user-specific resource filter for P6 Team Member Web.", alias="TeamMemberResourceFilter")
    team_member_display_qr_quick_access: Optional[StrictStr] = Field(default=None, description="The flag that is used to to determine if a user has seen the QR quick access link in P6 Team Member Web.", alias="TeamMemberDisplayQRQuickAccess")
    team_member_task_status_filter: Optional[StrictStr] = Field(default=None, description="The task status filter for P6 Team Member Web.", alias="TeamMemberTaskStatusFilter")
    team_member_timeframe_filter: Optional[StrictStr] = Field(default=None, alias="TeamMemberTimeframeFilter")
    team_member_wbs_filter: Optional[StrictStr] = Field(default=None, description="The time frame filter for P6 Team Member Web.", alias="TeamMemberWBSFilter")
    team_member_work_unit_type: Optional[StrictStr] = Field(default=None, description="The user-specific wbs filter for P6 Team Member Web.", alias="TeamMemberWorkUnitType")
    units_per_time_show_as_percentage: Optional[StrictBool] = Field(default=None, description="The flag which when set to true will show Units/Time as Percentage, and when set to false will display as Units/Duration. Possible values : 'True' or 'False'", alias="UnitsPerTimeShowAsPercentage")
    user_interface_view_object_id: Optional[StrictInt] = Field(default=None, description="The unique ID of the associated user interface view.", alias="UserInterfaceViewObjectId")
    __properties: ClassVar[List[str]] = ["AllResourceAccessFlag", "AssignmentStaffingPreference", "CreateDate", "CreateUser", "CurrencyId", "CurrencyName", "CurrencyObjectId", "CurrencyShowDecimals", "CurrencyShowSymbol", "DateFormatType", "DateSeparator", "DateShowFourDigitYear", "DateShowMinutes", "DateTimeFormatType", "DateUseLeadingZero", "DateUseMonthName", "DurationDecimalCount", "DurationUnitType", "DurationUseFraction", "EmailAddress", "EmailProtocol", "EnableUserToModifyViewSettingsFlag", "FinancialPeriodEndObjectId", "FinancialPeriodStartObjectId", "GUID", "GlobalProfileObjectId", "LastUpdateDate", "LastUpdateUser", "MailServerLoginName", "Name", "NewProjectDurationType", "ObjectId", "OfficePhone", "OutgoingMailServer", "PersonalName", "RateSourcePreference", "ReportingFlag", "ResourceRequests", "RespectActivityDurationType", "RoleLimitDisplayOption", "ShowDurationTimeUnit", "ShowTimeUnit", "SmallScaleDecimalCount", "SmallScaleUnitType", "SmallScaleUseFraction", "TeamMemberActivityFilters", "TeamMemberActivitySortField", "TeamMemberActivitySortOrder", "TeamMemberApplicationTheme", "TeamMemberDateFormat", "TeamMemberDisplayTimeFlag", "TeamMemberDisplayTimeFormat", "TeamMemberLocale", "TeamMemberProjectFilter", "TeamMemberResourceFilter", "TeamMemberDisplayQRQuickAccess", "TeamMemberTaskStatusFilter", "TeamMemberTimeframeFilter", "TeamMemberWBSFilter", "TeamMemberWorkUnitType", "UnitsPerTimeShowAsPercentage", "UserInterfaceViewObjectId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resource_requests
        if self.resource_requests:
            _dict['ResourceRequests'] = self.resource_requests.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AllResourceAccessFlag": obj.get("AllResourceAccessFlag"),
            "AssignmentStaffingPreference": obj.get("AssignmentStaffingPreference"),
            "CreateDate": obj.get("CreateDate"),
            "CreateUser": obj.get("CreateUser"),
            "CurrencyId": obj.get("CurrencyId"),
            "CurrencyName": obj.get("CurrencyName"),
            "CurrencyObjectId": obj.get("CurrencyObjectId"),
            "CurrencyShowDecimals": obj.get("CurrencyShowDecimals"),
            "CurrencyShowSymbol": obj.get("CurrencyShowSymbol"),
            "DateFormatType": obj.get("DateFormatType"),
            "DateSeparator": obj.get("DateSeparator"),
            "DateShowFourDigitYear": obj.get("DateShowFourDigitYear"),
            "DateShowMinutes": obj.get("DateShowMinutes"),
            "DateTimeFormatType": obj.get("DateTimeFormatType"),
            "DateUseLeadingZero": obj.get("DateUseLeadingZero"),
            "DateUseMonthName": obj.get("DateUseMonthName"),
            "DurationDecimalCount": obj.get("DurationDecimalCount"),
            "DurationUnitType": obj.get("DurationUnitType"),
            "DurationUseFraction": obj.get("DurationUseFraction"),
            "EmailAddress": obj.get("EmailAddress"),
            "EmailProtocol": obj.get("EmailProtocol"),
            "EnableUserToModifyViewSettingsFlag": obj.get("EnableUserToModifyViewSettingsFlag"),
            "FinancialPeriodEndObjectId": obj.get("FinancialPeriodEndObjectId"),
            "FinancialPeriodStartObjectId": obj.get("FinancialPeriodStartObjectId"),
            "GUID": obj.get("GUID"),
            "GlobalProfileObjectId": obj.get("GlobalProfileObjectId"),
            "LastUpdateDate": obj.get("LastUpdateDate"),
            "LastUpdateUser": obj.get("LastUpdateUser"),
            "MailServerLoginName": obj.get("MailServerLoginName"),
            "Name": obj.get("Name"),
            "NewProjectDurationType": obj.get("NewProjectDurationType"),
            "ObjectId": obj.get("ObjectId"),
            "OfficePhone": obj.get("OfficePhone"),
            "OutgoingMailServer": obj.get("OutgoingMailServer"),
            "PersonalName": obj.get("PersonalName"),
            "RateSourcePreference": obj.get("RateSourcePreference"),
            "ReportingFlag": obj.get("ReportingFlag"),
            "ResourceRequests": ResourceRequests.from_dict(obj["ResourceRequests"]) if obj.get("ResourceRequests") is not None else None,
            "RespectActivityDurationType": obj.get("RespectActivityDurationType"),
            "RoleLimitDisplayOption": obj.get("RoleLimitDisplayOption"),
            "ShowDurationTimeUnit": obj.get("ShowDurationTimeUnit"),
            "ShowTimeUnit": obj.get("ShowTimeUnit"),
            "SmallScaleDecimalCount": obj.get("SmallScaleDecimalCount"),
            "SmallScaleUnitType": obj.get("SmallScaleUnitType"),
            "SmallScaleUseFraction": obj.get("SmallScaleUseFraction"),
            "TeamMemberActivityFilters": obj.get("TeamMemberActivityFilters"),
            "TeamMemberActivitySortField": obj.get("TeamMemberActivitySortField"),
            "TeamMemberActivitySortOrder": obj.get("TeamMemberActivitySortOrder"),
            "TeamMemberApplicationTheme": obj.get("TeamMemberApplicationTheme"),
            "TeamMemberDateFormat": obj.get("TeamMemberDateFormat"),
            "TeamMemberDisplayTimeFlag": obj.get("TeamMemberDisplayTimeFlag"),
            "TeamMemberDisplayTimeFormat": obj.get("TeamMemberDisplayTimeFormat"),
            "TeamMemberLocale": obj.get("TeamMemberLocale"),
            "TeamMemberProjectFilter": obj.get("TeamMemberProjectFilter"),
            "TeamMemberResourceFilter": obj.get("TeamMemberResourceFilter"),
            "TeamMemberDisplayQRQuickAccess": obj.get("TeamMemberDisplayQRQuickAccess"),
            "TeamMemberTaskStatusFilter": obj.get("TeamMemberTaskStatusFilter"),
            "TeamMemberTimeframeFilter": obj.get("TeamMemberTimeframeFilter"),
            "TeamMemberWBSFilter": obj.get("TeamMemberWBSFilter"),
            "TeamMemberWorkUnitType": obj.get("TeamMemberWorkUnitType"),
            "UnitsPerTimeShowAsPercentage": obj.get("UnitsPerTimeShowAsPercentage"),
            "UserInterfaceViewObjectId": obj.get("UserInterfaceViewObjectId")
        })
        return _obj


